### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'websockets'

### ISSUE THREAD

**Issue by sig9org** [erm/mangum-examples#1]
# Summary

`TypeError: __init__() missing 1 required positional argument: 'websockets'`

# Environment

- CentOS 8.1.1911
- Python 3.8.1
- dfcf385d85dc127c4304b62200d4586d2c05ffd7, 

# Detail

I see the following error:

```
$ git clone https://github.com/erm/mangum-examples
$ pip install fastapi mangum[full] mangum-cli
$ cd mangum-examples/fastapi
$ mangum build
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.8.1/bin/mangum", line 11, in <module>
    load_entry_point('mangum-cli==0.0.1', 'console_scripts', 'mangum')()
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/mangum_cli/__main__.py", line 4, in main
    mangum_cli()
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/mangum_cli/commands.py", line 92, in build
    config = get_config()
  File "/usr/local/pyenv/versions/3.8.1/lib/python3.8/site-packages/mangum_cli/commands.py", line 29, in get_config
    config = Config(**config_data)
TypeError: __init__() missing 1 required positional argument: 'websockets'
```

**Comment by sig9org** [comment]
Closed because it is not reproduced.
